version: '2'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    links:
      - db
    volumes:
      - ".:/app"
    command: go build -o ./alpaca && ./alpaca

  db:
    image: mysql
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
